apiVersion: skaffold/v2beta28
kind: Config
metadata:
  name: kube-schedule-scaler
build:
  local:
    push: true
  artifacts:
  - image: registry.dev/kube-schedule-scaler
    docker:
      dockerfile: Dockerfile
deploy:
  helm:
    releases:
    - name: kube-schedule-scaler
      namespace: kube-schedule-scaler
      chartPath: charts
      artifactOverrides:
        image: registry.dev/kube-schedule-scaler
      imageStrategy:
        helm: {}
