apiVersion: apps/v1
kind: Deployment
metadata:
  name: nginx-deployment
  annotations:
    zalando.org/schedule-actions: |
      [
        {"schedule": "* * * * Mon-Wed", "replicas": "5"},
        {"schedule": "* * * * Thu-Fri", "replicas": "3"},
        {"schedule": "* * * * Sat-Sun", "replicas": "0"}
      ]
spec:
  selector:
    matchLabels:
      app: nginx
  replicas: 2 # tells deployment to run 2 pods matching the template
  template:
    metadata:
      labels:
        app: nginx
    spec:
      containers:
      - name: nginx
        image: nginx:1.14.2
        ports:
        - containerPort: 80
